version: "3"
   
services:
  psql:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - psqldata:/var/lib/postgresql/data
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=mongo
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGODB_DATA_DIR=/data/db
      - MONDODB_LOG_DIR=/dev/null
    volumes: 
      - mongodbdata:/data/db
  neo4j:
    image: neo4j
    volumes:
        - ./data/neo4j:/data
    ports:
      - 7474:7474
      - 7687:7687
    environment: 
      - NEO4J_AUTH=neo4j/admin
  redis:
    image: redis
    volumes:
        - ./data/redis:/data
  web:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8001:80
    depends_on:
      - psql
      - mongo
      - neo4j
      - redis
    environment: 
      - PYTHONUNBUFFERED=1

volumes:
  mongodbdata:
    driver: local
  psqldata:
    driver: local
